WebModule/src/main/java/ca/ryerson/scs/cscu/HelloBean.java
package ca.ryerson.scs.cscu;

import ca.ryerson.scs.cscu.ejb.MessageBean;
import ca.ryerson.scs.cscu.ejb.database.Programs.ProgramBean;

import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import javax.sql.DataSource;
import java.io.Serializable;

/**
 * Created by mitchellmohorovich on 15-07-11.
 */

@Named("helloBean")
@SessionScoped
public class HelloBean implements Serializable {

    @Resource(name = "jdbc/ResourceBank")
    DataSource ds;


    @EJB
    MessageBean mb;

    @EJB
    ProgramBean pb;

    String message = "message was not overridden";
    String dataSource;

    public String getMessage() {
        if(mb != null)
            this.setMessage(mb.getMessage());
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String dataSourceExists() {
        return String.valueOf((ds != null));
    }

    public String testConnection() {
        if(pb == null)
            return "ProgramBean is null.";
        else
            return String.valueOf(pb.entityManagerExists());
    }

    public void addProgram(String faculty, String shortName) {
        pb.addProgram(faculty, shortName);
    }
}

WebModule/src/main/java/ca/ryerson/scs/cscu/admin/AdminCourseBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.ejb.database.Courses.CourseBean;
import ca.ryerson.scs.cscu.entities.Course;
import ca.ryerson.scs.cscu.entities.Exam;
import ca.ryerson.scs.cscu.interfaces.AdminBean;
import ca.ryerson.scs.cscu.interfaces.DisplayBean;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Created by mitchellmohorovich on 15-07-19.
 */
@Named("adminCourseBean")
@RequestScoped
public class AdminCourseBean implements AdminBean<Course>, DisplayBean<Course> {
    @EJB
    CourseBean courseBean;
    private String courseCode;
    private String name;

    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }

    public String getCourseCode() {
        return courseCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Course findCourseByCourseCode(String courseCode) {
        return courseBean.getCourseByCourseCode(courseCode);
    }

    @Override
    public void persistEntity() throws IOException {
        courseBean.addCourse(new Course(this.getCourseCode(), this.getName()));
        ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
        ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
    }

    @Override
    public void removeEntityById(int id) {
        //todo: implement this
    }

    @Override
    public List<Course> getAllEntities() {
        return courseBean.getAllCourses();
    }

    public Map<String, Course> getAllEntitiesAsMap() {
        List<Course> allEntities = this.getAllEntities();
        Map<String, Course> allCourseMap = allEntities.stream().collect(Collectors.toMap(Course::getCourseCode, Function.identity()));
        return allCourseMap;
    }

    @Override
    public Course findEntityById(int id) {
        return courseBean.getCourseById(id);
    }

    public void addExamToCourseByCourseCode(String courseCode, Exam exam) {
        this.findCourseByCourseCode(courseCode).addExam(exam);
    }

    public void addExamToCourseById(int id, Exam exam) {
        this.findEntityById(id).addExam(exam);
    }

    public Map<String, Course> getAllEntitiesDifference(List<Course> courseList) {
        Map<String, Course> allCourseMap = this.getAllEntitiesAsMap();
        for(Course c: courseList) {
            allCourseMap.remove(c.getCourseCode());
        }
        return allCourseMap;
    }

}

WebModule/src/main/java/ca/ryerson/scs/cscu/admin/AdminCourseManagementFormBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.ejb.database.Courses.CourseManagementForms.CourseManagementFormBean;
import ca.ryerson.scs.cscu.entities.CourseManagementForm;

import javax.ejb.EJB;

/**
 * Created by mitchellmohorovich on 15-08-21.
 */
public class AdminCourseManagementFormBean {
    @EJB
    CourseManagementFormBean courseManagementFormBean;
    private final int MINIMUM_YEAR = 1995;
    private CourseManagementForm cmf;
}

WebModule/src/main/java/ca/ryerson/scs/cscu/admin/AdminExamBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.abstractClasses.TimeDocumentHandler;
import ca.ryerson.scs.cscu.ejb.database.Courses.CourseBean;
import ca.ryerson.scs.cscu.ejb.database.Courses.Exams.ExamBean;
import ca.ryerson.scs.cscu.entities.Exam;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.*;

/**
 * Created by mitchellmohorovich on 15-07-24.
 */
@Named("adminExamBean")
@RequestScoped
public class AdminExamBean extends TimeDocumentHandler {
    @EJB
    ExamBean examBean;

    @EJB
    CourseBean courseBean;

    private Exam.Type type; //Exam, Test, Practice Test, Practice Exam
    private Exam exam;
    @ManagedProperty("#{param.courseCode}")
    private String courseCode;

    private final int MINIMUM_YEAR = 1995;

    public void setType(Exam.Type type) {
        this.type = type;
    }

    public Exam.Type getType() {
        return type;
    }

    public Exam newExam(String courseCode) {
        Exam returnExam = new Exam(this.getYear(), this.getSemester(), this.getType());
        returnExam.setOwnerCourse(courseBean.getCourseByCourseCode(courseCode));
        returnExam.setFile(this.toByteArray(this.getUploadedFile()));
        return returnExam;
    }

    public void buildNewExam(String uriCourseCode) throws IOException {
        courseBean.addExamToCourse(uriCourseCode, examBean.addExam(this.newExam(uriCourseCode)));
        FacesContext.getCurrentInstance().getExternalContext().redirect("/courses/" + uriCourseCode);
    }

    public Exam getExamById(int id) {
        return examBean.getExamById(id);
    }

    public Exam.Type[] getTypes() {
        return Exam.Type.values();
    }

    public String setEditable(Exam e) {
        e.setEditable(true);
        return null;
    }

    public String editExam(String uriExamId) throws IOException {
        int intExamId = Integer.parseInt(uriExamId);
        examBean.setExamSemester(intExamId, this.getExam().getSemester());
        examBean.setExamType(intExamId, this.getExam().getType());
        examBean.setExamYear(intExamId, this.getExam().getYear());
        String ownerCourseCode = getExamById(Integer.parseInt(uriExamId)).getOwnerCourse().getCourseCode();
        FacesContext.getCurrentInstance().getExternalContext().redirect("/courses/" + ownerCourseCode);
        return String.valueOf(Integer.parseInt(uriExamId));
    }

    public void setExamType(int examId, Exam.Type type) {
        examBean.setExamType(examId, type);
    }

    public Exam getExam() {
        if(this.exam == null) {
            this.exam = new Exam();
        }
        return exam;
    }

    public void setExam(Exam exam) {
        this.exam = exam;
    }

    public void deleteExamById(int id) throws IOException {
        FacesContext.getCurrentInstance().getExternalContext().redirect("/courses/" + examBean.getExamById(id).getOwnerCourse().getCourseCode());
        examBean.deleteExam(id);
    }

    public String getCourseCode() {
        return courseCode;
    }

    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
}

WebModule/src/main/java/ca/ryerson/scs/cscu/admin/AdminFacultyBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.ejb.database.Faculty.FacultyBean;
import ca.ryerson.scs.cscu.entities.Faculty;
import ca.ryerson.scs.cscu.interfaces.AdminBean;
import ca.ryerson.scs.cscu.interfaces.DisplayBean;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;

/**
 * Created by mitchellmohorovich on 15-07-17.
 */

@Named("adminFacultyBean")
@RequestScoped
public class AdminFacultyBean implements AdminBean<Faculty>, DisplayBean<Faculty> {
    @EJB
    FacultyBean facultyBean;
    private String name;
    private List<Faculty> facultyList;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void addFaculty() throws IOException {
        facultyBean.addFaculty(this.getName());
        ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
        ec.redirect( ((HttpServletRequest) ec.getRequest()).getRequestURI());
    }

    @Override
    public void persistEntity() throws IOException {
        facultyBean.addFaculty(this.getName());
        ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
        ec.redirect( ((HttpServletRequest) ec.getRequest()).getRequestURI());
    }

    @Override
    public void removeEntityById(int id) {
        //todo: implement this
    }

    @Override
    public List<Faculty> getAllEntities() {
        return facultyBean.getAllFaculties();
    }

    @Override
    public Faculty findEntityById(int id) {
        return facultyBean.findFacultyById(id);
    }
}

WebModule/src/main/java/ca/ryerson/scs/cscu/admin/AdminProgramBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.ejb.database.Faculty.FacultyBean;
import ca.ryerson.scs.cscu.ejb.database.Programs.ProgramBean;
import ca.ryerson.scs.cscu.entities.Faculty;
import ca.ryerson.scs.cscu.entities.Program;
import ca.ryerson.scs.cscu.interfaces.AdminBean;
import ca.ryerson.scs.cscu.interfaces.DisplayBean;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.validator.FacesValidator;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;

/**
 * Created by mitchellmohorovich on 15-07-16.
 */

@Named("adminProgramBean")
@RequestScoped
public class AdminProgramBean implements AdminBean<Program>, DisplayBean<Program> {
    @EJB
    ProgramBean programBean;

    @EJB
    FacultyBean facultyBean;

    String name;
    String shortName;
    int facultyId;
    List<Program> allPrograms;
    int programId;
    int courseId;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getshortName() {
        return shortName;
    }

    public void setshortName(String shortName) {
        this.shortName = shortName;
    }

    public void setFacultyId(int facultyId) {
        this.facultyId = facultyId;
    }

    public int getFacultyId() {
        return facultyId;
    }

    public List<Program> getAllPrograms() {
        if(this.allPrograms == null)
            this.allPrograms = programBean.getAllPrograms();
        return programBean.getAllPrograms();
    }

    public Program getProgramByShortName(String shortName) {
        return programBean.getProgramByShortName(shortName);
    }

    @Override
    public void persistEntity() throws IOException {
        Faculty faculty = facultyBean.findFacultyById(this.getFacultyId());
        programBean.addProgram(this.getName(), this.getshortName(), faculty);
        ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
        ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
    }

    @Override
    public void removeEntityById(int id) {
        //todo: implement this
    }

    @Override
    public List<Program> getAllEntities() {
        return programBean.getAllPrograms();
    }

    @Override
    public Program findEntityById(int id) {
        return programBean.getProgramById(id);
    }

    public void addCourseToProgram(int courseId, int programId) {
    }

    public void addCourseToProgramByShortCode(int courseId, String shortCode) {
        programBean.addCourseToProgramByShortName(courseId, shortCode);
    }

    public int getCourseId() {
        return courseId;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
}

WebModule/src/main/java/ca/ryerson/scs/cscu/admin/EditCMFBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.abstractClasses.TimeDocumentHandler;
import ca.ryerson.scs.cscu.ejb.database.Courses.CourseManagementForms.CourseManagementFormBean;
import ca.ryerson.scs.cscu.entities.CourseManagementForm;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Created by mitchellmohorovich on 15-08-25.
 */
@Named("editCMFBean")
@RequestScoped
public class EditCMFBean extends TimeDocumentHandler {
    @EJB
    CourseManagementFormBean courseManagementFormBean;

    private int id;
    private CourseManagementForm cmf;
    private short year;

    /**
     * Given that the id is valid and returns a cmf, initializes the cmf.
     * Otherwise redirects.
     */
    public void initialize() throws IOException {
        this.setCmf(courseManagementFormBean.getCourseManagementFormById(this.getId()));
        if(this.cmf == null) {
            FacesContext context = FacesContext.getCurrentInstance();
            context.getExternalContext().responseSendError(404, "That course management form does not exist.");
            context.responseComplete();
        }
    }

    public void editCMF(int id) throws IOException {
        courseManagementFormBean.setSemester(id, this.getCmf().getSemester());
        courseManagementFormBean.setYear(id, this.getCmf().getYear());
        FacesContext.getCurrentInstance().getExternalContext().redirect("/courses/" + this.getCourseManagementFormById(id).getOwnerCourse().getCourseCode());
    }

    public void deleteCourseManagementFormById(int id) throws IOException {
        FacesContext.getCurrentInstance().getExternalContext().redirect("/courses/" + courseManagementFormBean.getCourseManagementFormById(id).getOwnerCourse().getCourseCode());
        courseManagementFormBean.deleteCourseManagementForm(id);
    }

    public CourseManagementForm getCmf() {
        if(this.cmf == null) {
            this.cmf = new CourseManagementForm();
        }
        return cmf;
    }

    public void setCmf(CourseManagementForm courseManagementForm) {
        this.cmf = courseManagementForm;
    }

    public CourseManagementForm getCourseManagementFormById(int id) {
        return courseManagementFormBean.getCourseManagementFormById(id);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void validate(FacesContext context, UIComponent uiComponent, Object object) {
        if((Integer) object <= 0) {
            context.getExternalContext().setResponseStatus(404);
        } else if(this.getCourseManagementFormById(this.getId()) == null) {
            context.getExternalContext().setResponseStatus(404);
        }
    }

}

WebModule/src/main/java/ca/ryerson/scs/cscu/interfaces/AdminBean.java
package ca.ryerson.scs.cscu.interfaces;

import java.io.IOException;

/**
 * Created by mitchellmohorovich on 15-07-22.
 */
public interface AdminBean<E> {
    void persistEntity() throws IOException;
    void removeEntityById(int id);
}

WebModule/src/main/java/ca/ryerson/scs/cscu/security/SecurityBean.java
package ca.ryerson.scs.cscu.security;

import javax.enterprise.context.RequestScoped;
import javax.faces.FacesException;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

/**
 * Created by mitchellmohorovich on 15-07-12.
 */

@Named(value = "securityBean")
@RequestScoped
public class SecurityBean {
    private static String ADMIN_ROLE = "admin";
    private static String USER_ROLE = "user";

    private HttpServletRequest getHttpServletRequest() {
        return (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
    }

    public String getUserName() {
        HttpServletRequest request = this.getHttpServletRequest();
        if (request.getUserPrincipal() != null) {
            return request.getUserPrincipal().getName();
        } else {
            return "";
        }
    }

    public boolean isUserAdmin() {
        return (this.getHttpServletRequest().isUserInRole(ADMIN_ROLE));
    }

    public boolean isLoggedIn() {
        return (this.getHttpServletRequest().getUserPrincipal() != null);
    }

    public void logout() {
        try {
            this.getHttpServletRequest().logout();
            this.getHttpServletRequest().getSession().invalidate();
        } catch (ServletException e) {
            throw new FacesException("Failure on logout", e);
        }
    }
}

WebModule/src/main/webapp/about.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <h1>About</h1>
            <h2>Resource Bank</h2>
            <p>
                The Resource Bank is the replacement for the CSCU's Exam Bank. It was completely rewritten to be a self-contained and self-hosted application on campus. It features web-based administration so anyone is able to easily upload, edit and modify content on the site.
            </p>
            <p>
                All files on the site were uploaded by students or professors, and belong to their respective owners. If you see any content on this site that you do not with to be available for students, contact us at cscu@scs.ryerson.ca.
            </p>
            <p>
                The site is hosted on the servers of the Department of Computer Science. A special thanks to Ivan Rubiales for his help.
            </p>
            <p>For technical information about the project, see the <a href="https://github.com/iMiiTH/ResourceBank">Github <i class="glyphicon glyphicon-expand"/></a> page!</p>
            <h2>About the Developers</h2>
            <p>
                The Resource Bank is a collaborative effort by students, for students in Computer Science at Ryerson University. Development was led by Mitchell Mohorovich, with help from David Tenty and Frank Vumbaca.
            </p>
        </ui:define>
    </ui:composition>
</h:body>
</html>

WebModule/src/main/webapp/contact.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <h1>Contact</h1>
            <div class="row">
                <div class="hidden-xs col-sm-5 pull-right">
                    <img class="thumbnail img-responsive" src="resources/images/eng111.jpg"/>
                </div>
                <div class="col-xs-12 col-sm-7">
                    <p>The Resource Bank is currently being maintained by the Computer Science Course Union (CSCU).</p>
                    <p>If you have any questions, comments, concern or suggestions for the site, email us at cscu@scs.ryerson.ca.</p>
                    <p>You're always (and encouraged) to email any saved or previous exams/cmf's you have to us, or bring them to our office at ENG-111 to have them digitized.</p>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</h:body>
</html>

WebModule/src/main/webapp/error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <p>There was an error logging you in.</p>
        </ui:define>
    </ui:composition>
</h:body>
</html>

WebModule/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">

        <ui:define name="pre-container">
            <h:outputStylesheet library="css" name="landing.min.css" target="head"/>
            <h:outputStylesheet library="css" name="table-link.min.css" target="head"/>
            <div class="wide">
                <div class="logo h1">CSCU<br /> Resource Bank</div>
            </div>
        </ui:define>

        <ui:define name="content">
            <div class="row">
                <div class="col-sm-6">
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <i class="glyphicon glyphicon-alert"/> Hardhats required
                        </div>
                        <div class="panel-body">
                            <p>This site is still in beta. From time to time the application will cease to function. In case that ever happens, remember the old Exam Bank is still online at <a href="http://exams.cscu.scs.ryerson.ca">exams.cscu.scs.ryerson.ca</a>.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a class="btn-block" href="/programs/CS">Enter</a>
                        </div>
                        <div class="panel-body">
                            <p>While this site may not be 100% bug free, nor does it have as many exams (yet), it does have infinitely more course management forms. So go ahead and <a href="/programs/CS">check it out</a>.</p>
                        </div>
                    </div>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</h:body>
</html>

WebModule/src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="title">
            <title>Resource Bank - Login</title>
        </ui:define>
        <ui:define name="content">
            <h1>Login</h1>
            <form method="POST" action="j_security_check">
                <div class="form-group">
                    <h:outputLabel value="Username:">
                        <input class="form-control" type="text" name="j_username"/>
                    </h:outputLabel>
                </div>
                <div class="form-group">
                    <h:outputLabel value="Password:">
                        <input class="form-control" type="password" name="j_password"/>
                    </h:outputLabel>
                </div>
                <br/>
                <div class="form-group">
                    <input class="btn" type="submit" value="Login"/>
                    <input class="btn" type="reset" value="Reset"/>
                </div>
            </form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

WebModule/src/main/webapp/logout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:metadata>
    <f:viewAction action="#{securityBean.logout}"/>
</f:metadata>
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <h1>Logged Out</h1>
            <h:outputLabel value="You are logged out." rendered="#{!securityBean.loggedIn}"/>
            <h:outputLabel value="There was an error logging you out." rendered="#{securityBean.loggedIn}"/>
        </ui:define>
    </ui:composition>
</h:body>
</html>