WebModule/src/main/java/ca/ryerson/scs/cscu/admin/AdminFacultyBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.ejb.database.Faculty.FacultyBean;
import ca.ryerson.scs.cscu.entities.Faculty;
import ca.ryerson.scs.cscu.interfaces.AdminBean;
import ca.ryerson.scs.cscu.interfaces.DisplayBean;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;

/**
 * Created by mitchellmohorovich on 15-07-17.
 */

@Named("adminFacultyBean")
@RequestScoped
public class AdminFacultyBean implements AdminBean<Faculty>, DisplayBean<Faculty> {
    @EJB
    FacultyBean facultyBean;
    private String name;
    private List<Faculty> facultyList;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void addFaculty() throws IOException {
        facultyBean.addFaculty(this.getName());
        ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
        ec.redirect( ((HttpServletRequest) ec.getRequest()).getRequestURI());
    }

    @Override
    public void persistEntity() throws IOException {
        facultyBean.addFaculty(this.getName());
        ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
        ec.redirect( ((HttpServletRequest) ec.getRequest()).getRequestURI());
    }

    @Override
    public void removeEntityById(int id) {
        //todo: implement this
    }

    @Override
    public List<Faculty> getAllEntities() {
        return facultyBean.getAllFaculties();
    }

    @Override
    public Faculty findEntityById(int id) {
        return facultyBean.findFacultyById(id);
    }
}

WebModule/src/main/java/ca/ryerson/scs/cscu/security/SecurityBean.java
package ca.ryerson.scs.cscu.security;

import javax.enterprise.context.RequestScoped;
import javax.faces.FacesException;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

/**
 * Created by mitchellmohorovich on 15-07-12.
 */

@Named(value = "securityBean")
@RequestScoped
public class SecurityBean {
    private static String ADMIN_ROLE = "admin";
    private static String USER_ROLE = "user";

    private HttpServletRequest getHttpServletRequest() {
        return (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
    }

    public String getUserName() {
        HttpServletRequest request = this.getHttpServletRequest();
        if (request.getUserPrincipal() != null) {
            return request.getUserPrincipal().getName();
        } else {
            return "";
        }
    }

    public boolean isUserAdmin() {
        return (this.getHttpServletRequest().isUserInRole(ADMIN_ROLE));
    }

    public boolean isLoggedIn() {
        return (this.getHttpServletRequest().getUserPrincipal() != null);
    }

    public void logout() {
        try {
            this.getHttpServletRequest().logout();
            this.getHttpServletRequest().getSession().invalidate();
        } catch (ServletException e) {
            throw new FacesException("Failure on logout", e);
        }
    }
}

WebModule/src/main/webapp/courses/course.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:metadata>
    <f:viewParam name="refCourse" value="#{courseDisplayBean.refCourse}"/>
    <f:viewAction action="#{breadcrumbBean.addBreadcrumbs(courseDisplayBean.generateBreadcrumbs(uriCourseCode))}"/>

</f:metadata>
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="title">
            <title>Resource Bank - #{uriCourseCode}</title>
        </ui:define>

        <ui:define name="content">
            <h:outputScript library="js" name="table-link.js" target="head"/>
            <h:outputStylesheet library="css" name="table-link.min.css" target="head"/>

            <div class="page-header">
                <h1>#{uriCourseCode}:
                    <small>#{courseDisplayBean.findCourseByCourseCode(uriCourseCode).name}</small>
                </h1>
            </div>
            <h2>Course Managment Forms:
            </h2>
            <div class="row">
                <div class="col-lg-12">
                    <h:dataTable styleClass="table table-hover" value="#{courseDisplayBean.findCourseByCourseCode(uriCourseCode).courseManagementForms}" var="cmf" rowClasses="clickable-row">
                        <f:passThroughAttribute name="data-href" value="/downloads/cmfs/cmf?id=#{cmf.id}"/>
                        <h:column>
                            <f:facet name="header">Semester</f:facet>
                            #{cmf.semester.label}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Year</f:facet>
                            #{cmf.year}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Uploaded</f:facet>
                            #{cmf.formattedUploadDate}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Download</f:facet>
                            <a href="/downloads/cmfs/cmf?id=#{cmf.id}"><i class="glyphicon glyphicon-download"/></a>
                        </h:column>
                        <h:column rendered="#{securityBean.userAdmin}">
                            <f:facet name="header">Edit</f:facet>
                            <a href="/admin/cmfs/cmf.xhtml?id=#{cmf.id}"><i class="glyphicon glyphicon-pencil"/></a>
                        </h:column>
                    </h:dataTable>
                </div>
            </div>
            <h:panelGroup layout="block" styleClass="row" rendered="#{securityBean.userAdmin}">
                <div class="col-lg-12">
                    <a href="/admin/cmfs/add.xhtml?courseCode=#{uriCourseCode}" class="btn btn-success btn-sm pull-left">Add New CMF</a>
                </div>
            </h:panelGroup>
            <div class="row">
                <div class="col-lg-12">
                    <h2>Test List:</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h:dataTable styleClass="table table-hover" value="#{courseDisplayBean.findCourseByCourseCode(uriCourseCode).exams}" var="ce" rowClasses="clickable-row">
                        <f:passThroughAttribute name="data-href" value="/downloads/exams/exam?id=#{ce.id}"/>
                        <h:column>
                            <f:facet name="header">Type</f:facet>
                            #{ce.type.label}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Semester</f:facet>
                            #{ce.semester.label}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Year</f:facet>
                            #{ce.year}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Uploaded</f:facet>
                            #{ce.formattedUploadDate}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Download</f:facet>
                            <a href="/downloads/exams/exam?id=#{ce.id}"><i class="glyphicon glyphicon-download"/> </a>
                        </h:column>
                        <h:column rendered="#{securityBean.userAdmin}">
                            <f:facet name="header">Edit</f:facet>
                            <a href="/admin/exams/modify/#{ce.id}"><i class="glyphicon glyphicon-pencil"/></a>
                        </h:column>
                    </h:dataTable>
                </div>

            </div>
            <h:panelGroup layout="block" styleClass="row" rendered="#{securityBean.userAdmin}">
                <div class="col-lg-12">
                    <a href="/admin/exams/add.xhtml?courseCode=#{uriCourseCode}" class="btn btn-success btn-sm pull-left">Add New Exam</a>
                </div>
            </h:panelGroup>
        </ui:define>
    </ui:composition>
</h:body>
</html>

WebModule/src/main/webapp/courses/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:metadata>
    <f:viewAction action="#{breadcrumbBean.addActiveBreadcrumb('Courses')}"/>
</f:metadata>
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="title">
            <title>Resource Bank - All Courses</title>
        </ui:define>

        <ui:define name="content">
            <h:outputScript library="js" name="table-link.js" target="head"/>
            <h:outputStylesheet library="css" name="table-link.min.css" target="head"/>

            <h1>Courses <small>Master List</small></h1>
            <p>All courses available on the site are listed here, not organized by program relevance.</p>
            <h:dataTable styleClass="table table-hover" value="#{adminCourseBean.allEntities}" var="c" rowClasses="clickable-row">
                <f:passThroughAttribute name="data-href" value="/courses/#{c.courseCode}"/>
                <h:column>
                    <f:facet name="header">Course Code</f:facet>
                    <a href="/courses/#{c.courseCode}">
                        #{c.courseCode}
                    </a>
                </h:column>
                <h:column>
                    <f:facet name="header">Name</f:facet>
                    #{c.name}
                </h:column>
            </h:dataTable>

        </ui:define>
    </ui:composition>
</h:body>
</html>