WebModule/src/main/java/ca/ryerson/scs/cscu/admin/NewAdminCourseManagementFormBean.java
package ca.ryerson.scs.cscu.admin;

import ca.ryerson.scs.cscu.abstractClasses.TimeDocumentHandler;
import ca.ryerson.scs.cscu.ejb.database.Courses.CourseBean;
import ca.ryerson.scs.cscu.ejb.database.Courses.CourseManagementForms.CourseManagementFormBean;
import ca.ryerson.scs.cscu.entities.CourseManagementForm;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.IOException;
import java.util.Calendar;

/**
 * Created by mitchellmohorovich on 15-08-22.
 * Used to add a create new CMF's
 */

@Named("newAdminCMFBean")
@RequestScoped
public class NewAdminCourseManagementFormBean extends TimeDocumentHandler {
    @EJB
    CourseBean courseBean;

    @EJB
    CourseManagementFormBean courseManagementFormBean;

    /**
     * The courseCode parameter that is sent as a GET parameter.
     * It is populated in the cmfs/add.xhtml viewParam tag.
     */
    private String courseCode;
    private String professor;

    public void buildNewCMF() throws IOException {
        CourseManagementForm cmf = new CourseManagementForm(
                this.getYear(),
                this.getSemester(),
                this.getProfessor(),
                this.courseBean.getCourseByCourseCode(this.getCourseCode()));
        cmf.setFile(this.toByteArray(this.getUploadedFile()));
        cmf.setContentType(this.getUploadedFile().getContentType());
        courseManagementFormBean.addCourseManagementForm(cmf);
        courseBean.addCourseManagementFormToCourse(cmf, courseBean.getCourseByCourseCode(this.getCourseCode()).getId());
        FacesContext.getCurrentInstance().getExternalContext().redirect("/courses/" + courseCode);
    }

    public String getCourseCode() {
        return courseCode;
    }

    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }

    public int getCurrentYear() { return Calendar.getInstance().get(Calendar.YEAR);
    }

    public int[] getYearRange() {
        int size = this.getCurrentYear() - this.MINIMUM_YEAR + 1;
        int returnArray[] = new int[size];
        returnArray[0] = this.MINIMUM_YEAR;
        for (int i = 1; i < size; i++) {
            returnArray[i] = returnArray[i-1]+1;
        }
        return returnArray;
    }

    public String getProfessor() {
        return professor;
    }

    public void setProfessor(String professor) {
        this.professor = professor;
    }
}

WebModule/src/main/java/ca/ryerson/scs/cscu/downloads/exams/ExamDownloadServlet.java
package ca.ryerson.scs.cscu.downloads.exams;

/**
 * Created by mitchellmohorovich on 15-07-29.
 */

import ca.ryerson.scs.cscu.ejb.database.Courses.CourseBean;
import ca.ryerson.scs.cscu.ejb.database.Courses.Exams.ExamBean;
import ca.ryerson.scs.cscu.entities.Exam;

import java.awt.datatransfer.DataFlavor;
import java.io.*;
import javax.ejb.EJB;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class ExamDownloadServlet extends HttpServlet {

    private static final int BYTES_DOWNLOAD = 1024;

    @EJB
    ExamBean examBean;

    @EJB
    CourseBean courseBean;

    public void doGet(HttpServletRequest request,
                      HttpServletResponse response) throws IOException {
        int examID;
        try {
            examID = Integer.parseInt(request.getParameter("id"));
        } catch(NumberFormatException e) {
            response.sendError(HttpServletResponse.SC_NOT_ACCEPTABLE, "The id was invalid or not provided");
            return;
        }


        Exam exam = examBean.getExamById(examID);
        if(exam == null) {
            response.sendError(HttpServletResponse.SC_NOT_FOUND, "The exam with the ID " + examID + " does not exist.");
            return;
        }
        byte[] examFile = exam.getFile();
        if(examFile == null) {
            response.sendError(HttpServletResponse.SC_NOT_FOUND, "The exam file does not exist.");
            return;
        }

        //CourseCode_Year_Semester_Type
        //Ex.CPS590_2015_Fall_PracticeTest
        String filename = String.format("%s_%d_%s_%s",
                courseBean.getCourseById(exam.getOwnerCourse().getId()).getCourseCode(),
                exam.getYear(),
                exam.getSemester(),
                exam.getType()
        );

        response.setContentType(exam.getContentType());
        response.setHeader("Content-Disposition", "inline;filename=" + filename + ".pdf");

        BufferedOutputStream bos = null;
        BufferedInputStream bis = null;
        try {
            bos = new BufferedOutputStream(response.getOutputStream());
            bis = new BufferedInputStream(new ByteArrayInputStream(examFile));
            byte[] buffer = new byte[8192];
            for(int i; (i = bis.read(buffer)) > 0;) {
                bos.write(buffer, 0, i);
            }
            bos.flush();
        } finally {
            if(bos != null) {
                try {
                    bos.close();
                } catch (IOException e) {} //nothing we can do now
            }
            if(bis != null) {
                bis.close();
                try {
                    bis.close();
                } catch (IOException e) {} //nothing we can do now
            }
        }
    }
}

WebModule/src/main/webapp/admin/exams/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:c="http://java.sun.com/jstl/core">
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <div class="page-header">
                <h1>Add Exam
                    <small><h:outputText value="#{param['courseCode']}"/></small>
                </h1>
            </div>

            <ui:include src="/WEB-INF/templates/errors.xhtml"/>
            <h:form id="exam-form" styleClass="form-horizontal" enctype="multipart/form-data">
                <div class="form-group form-group-sm">
                    <h:outputLabel for="type-select" styleClass="col-md-2 control-label" value="Test Type:"/>

                    <div class="col-sm-10">
                        <h:selectOneMenu id="type-select" styleClass="form-control" value="#{adminExamBean.type}">
                            <f:selectItems value="#{adminExamBean.types}" var="type" itemValue="#{type}" itemLabel="#{type.label}"/>
                        </h:selectOneMenu>

                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <h:outputLabel for="year-select" styleClass="col-md-2 control-label" value="Year:"/>

                    <div class="col-md-10">
                        <h:selectOneMenu id="year-select" styleClass="form-control"
                                         value="#{adminExamBean.year}">
                            <f:selectItems value="#{adminExamBean.yearRange}" var="year" itemValue="#{year}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <h:outputLabel for="semester-select" styleClass="col-md-2 control-label" value="Semester:"/>

                    <div class="col-md-10">
                        <h:selectOneMenu id="semester-select" styleClass="form-control"
                                         value="#{adminExamBean.semester}">
                            <f:selectItems value="#{adminExamBean.semesters}" var="semester" itemValue="#{semester}" itemLabel="#{semester.label}"/>
                        </h:selectOneMenu>

                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <h:outputLabel value="Choose File:" styleClass="col-md-2 control-label" for="exam-file"/>
                    <div class="col-md-10">
                        <h:inputFile id="exam-file" value="#{adminExamBean.uploadedFile}" required="true"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        <h:commandButton type="submit" value="Add Exam" styleClass="btn btn-success" action="#{adminExamBean.buildNewExam(param['courseCode'])}"/>
                    </div>
                </div>
            </h:form>

        </ui:define>
    </ui:composition>
</h:body>
</html>

WebModule/src/main/webapp/admin/exams/exam.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:metadata>
    <f:event type="preRenderView" listener="#{adminExamBean.setExam(adminExamBean.getExamById(uriExamId))}"/>
</f:metadata>
<h:body>
    <ui:composition template="/WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <div class="page-header">
                <h1>Exam
                    <small>Administration</small>
                </h1>
                <p>Exam ##{uriExamId} of #{adminExamBean.exam.ownerCourse.courseCode}</p>
            </div>
            <ui:include src="/WEB-INF/templates/errors.xhtml"/>
            <h:form id="exam-edit-form" styleClass="form-horizontal">
                <div class="form-group form-group-sm">
                    <h:outputLabel for="type-select" styleClass="col-md-2 control-label" value="Test Type:"/>

                    <div class="col-sm-10">
                        <h:selectOneMenu id="type-select"
                                         styleClass="form-control"
                                         value="#{adminExamBean.exam.type}"
                                         validatorMessage="Type validation failed: Select value was modified.">
                            <f:selectItems value="#{adminExamBean.types}" var="type" itemValue="#{type}"
                                           itemLabel="#{type.label}"/>
                        </h:selectOneMenu>

                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <h:outputLabel for="year-select" styleClass="col-md-2 control-label" value="Year:"/>

                    <div class="col-md-10">
                        <h:selectOneMenu id="year-select"
                                         styleClass="form-control"
                                         value="#{adminExamBean.exam.year}"
                                         validatorMessage="Year validation failed: Select value was modified.">
                            <f:selectItems value="#{adminExamBean.yearRange}" var="year" itemValue="#{year}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <h:outputLabel for="semester-select" styleClass="col-md-2 control-label" value="Semester:"/>

                    <div class="col-md-10">
                        <h:selectOneMenu id="semester-select"
                                         styleClass="form-control"
                                         value="#{adminExamBean.exam.semester}"
                                         validatorMessage="Smeestervalidation failed: Select value was modified.">
                            <f:selectItems value="#{adminExamBean.semesters}" var="semester" itemValue="#{semester}" itemLabel="#{semester.label}"/>
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        <h:commandButton type="submit" styleClass="btn btn-success" value="Submit Changes" action="#{adminExamBean.editExam(uriExamId)}"/>
                        <h:commandButton type="submit" styleClass="btn btn-danger pull-right" value="Delete Exam" action="#{adminExamBean.deleteExamById(uriExamId)}"/>
                    </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>